project_id = "iqcoumkqgcbqdetuqozh"

[functions.generate-layout]
verify_jwt = false

[functions.export-layout]
verify_jwt = false

[functions.export-zip]
verify_jwt = false

[functions.generate-files]
verify_jwt = false

[functions.analyze-design]
verify_jwt = false
